name: 'Github Actions Notify Telegram'
description: 'Send a notification to a Telegram chat via a Telegram bot'
inputs:
  TELEGRAM_BOT_ID:  # id of input
    description: 'ID of the Telegram bot'
    required: true
    default: 'null'
  TELEGRAM_CHAT_ID:  # id of input
    description: 'ID of the chat. Telegram bot will send message to this chat'
    required: true
    default: 'null'
  STATUS:  # id of input
    description: 'status of the workflow you can pass status true || false '
    required: true
    default: 'true'

runs:
  using: 'node12'
  main: 'dist/index.js'
