name: "Github Actions Notify Telegram"
description: "Send a notification to a Telegram chat via a Telegram bot"
inputs:
  TELEGRAM_BOT_ID: # id of input
    description: "ID of the Telegram bot"
    required: true
    default: "null"
  TELEGRAM_CHAT_ID: # id of input
    description: "ID of the chat. Telegram bot will send message to this chat"
    required: true
    default: "null"
  STATUS: # id of input
    description: "status of the workflow . pass status true || false in 2 if conditions "
    required: true
    default: "true"
  CUSTOMMESSAGE:
    description: "Notify message send via the Telegram bot"
    required: true
    default: "Successfully Completed Github Action"

  JOBSTATUS:
    description: Job status"
    required: false
    default: "false"

  GITHUB_RUN_NUMBER:
    description: "GitHub Run Number"
    required: false
    default: "0"

  GITHUB_REPOSITORY:
    description: "GitHub Repository "
    required: false
    default: ""

  GITHUB_RUN_ID:
    description: "GitHub Run ID"
    required: false
    default: "0"

  GITHUB_ACTOR:
    description: "Triggered user"
    required: false
    default: ""

  GITHUB_EVENT_NAME:
    description: "Triggered event"
    required: false
    default: ""

  GITHUB_SHA:
    description: "GitHub commit SHA "
    required: false
    default: ""

runs:
  using: "node12"
  main: "dist/index.js"
