name: "Github Actions Notify Telegram"
description: "Send a notification to a Telegram chat via a Telegram bot"
inputs:
  TELEGRAM_BOT_ID: # id of input
    description: "ID of the Telegram bot"
    required: true
    default: "null"
  TELEGRAM_CHAT_ID: # id of input
    description: "ID of the chat. Telegram bot will send message to this chat"
    required: true
    default: "null"
  CUSTOMMESSAGESUCCESS:
    description: "Notify message send via the Telegram bot when success"
    required: true
    default: "Successfully Completed Github Action"
  CUSTOMMESSAGESFAILURE:
    description: "Notify message send via the Telegram bot when failed"
    required: true
    default: "Github Action Failed"
  CUSTOMMESSAGESCANCELLED:
    description: "Notify message send via the Telegram bot when cancelled"
    required: true
    default: "Github Action Cancled"

  JOBSTATUS:
    description: Job status"
    required: true
    default: "success"

  GITHUB_RUN_NUMBER:
    description: "GitHub Run Number"
    required: false
    default: "0"

  GITHUB_REPOSITORY:
    description: "GitHub Repository "
    required: false
    default: ""

  GITHUB_RUN_ID:
    description: "GitHub Run ID"
    required: false
    default: "0"

  GITHUB_ACTOR:
    description: "Triggered user"
    required: false
    default: ""

  GITHUB_EVENT_NAME:
    description: "Triggered event"
    required: false
    default: ""

  GITHUB_SHA:
    description: "GitHub commit SHA "
    required: false
    default: ""

runs:
  using: "node12"
  main: "dist/index.js"
