name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./index.js
      with:
        TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        STATUS: true
        CUSTOMMESSAGE: "Testing Gihub \xF0\x9F\x94\xAC Action For Telegram Notify Action \xF0\x9F\x94\xAE "
